language: node_js
node_js:
- '4'
sudo: false
branches:
  only:
  - master
script:
- echo "Nothing to build, no tests to run"
notifications:
  irc: irc.mozilla.org#communityops
before_deploy:
- gem install mime-types -v 2.6.2
deploy:
- provider: s3
  access_key_id: "AKIAINEOGQFBBZPB6RQQ"
  secret_access_key:
    secure: "A+izkFqOIj0p+e8SX6VI6BQ03PZzrnMS+wJZdyqvTPsFMu2Fjse2fqjWIup9mtfSdliBiGNnanYgop3WpBS7j87z4+UBCslsyei7K/wrYgik3fDzD00spi0Ag4krUO9186Oq0NEFTzyCgLmRj/O0nuyTqwk9EbmKFLQ3lVQgyZ3jsa/ZJXwmmY8j0cQfYa6IBCLUmgNZ5oAE0S/tDvQSSR3HyD748/vzhrNxlri//5i4mRIS5rcZ5BYjNlc+INCPrF4a3hm9447QDVrfVjAvqxvy+kzJlpn4ENs8feIwQpUGCS/4NAd74beJ/lJ6SoTQVW0Z4YVJocqxgGXhXeQSW8RrrmgPzP076w7puh4NFXbwuV6FrB1Y7Xk6xBIUmm7IRlwwuZ4jxbdtJBnnNmS3oFKm3lmSh+bXj1IHEw7fO1IJFiIB0g4eojk3ovMD9/lrNW8kMtCgHAADWtY6ef0nYy8HsCac7S4uYgfzGGP02D1X/VdBZu/8ZzqA+bu9pyf5BrbymWPYpUyBZCkBGty2/0jDvS8D+4H1za3vCYNMR99tFc+g9JHkkUkdy6EOjozLXL+xxFy7pMnvrmMLZhBUq1e4CyIljrpxLFA97zEFG7cinB4pEFrBdvexbiXlCkup4vZqg9jDLwsgb1/96ERzurJQxdgRGbtQ+c5btkur4B0="
  bucket: ops-blog
  skip_cleanup: true
  detect_encoding: true
  on:
    repo: mozilla-cit/discourse-api-js
    branch: master
