sudo: false
branches:
  only:
  - master
script:
- echo "Nothing to build, no tests to run"
notifications:
  irc: irc.mozilla.org#communityops
deploy:
- provider: s3
  access_key_id: AKIAJJEWDSBN7ZUUAPFQ
  secret_access_key:
    secure: "U/EzdD8cwPzisUl2B/sZ6EIv1VdPyymbtJqs6ZwubyBYsJtlbcIvwfUEbO/zxY8LCQQNTzHMdU7UeCS7a+NB2RhrkL5y+gWTXi1w0Tt9s9FObKQY/yZrqP1CvV5ViTDRBBG6KsSPEtl5Cd9ExwUBDZzS3ZXVb2vf5awzAJ+zVh6YVoHwtkoSZ0weu/Z+IuBmRJuIsol6LKoWB8krhlmWHWQlCy0I2kVftvp1AkMuHkd9iHWUb/vGR3i2hZm616AlhKqn5NNK4xXjKhPa8y7VKW990RIJ+QA3qDlnbDGaC3XnHnha3yXS8MQyT6LTzy7VhfpTjLyNzC27WeUFqMgLeZ3Bbf2MorZ9LkIi6AOr2uP88CJHDJ2AdnVOjJyfNhHGbKOaU0yvcfnq5ndgxUm2zskaqcZUGCaheAQ32iSsM6L3d9IYFU05Ybhrj2Kpp8HiLSoaVcFTaUxuHuIpzIyCvZKu2Y33gt2gd12t3vWJzPAFzIvtJ2gKg630a6pv982OWs2qO6mKOK4VIs1zkD5QdMGJ+Tc8LuHnEmj3EnBEkM2WR212kvoQXAdUqhQwLNKdcHDSAzsOnMmDlzWf1doltm8aEjPavuS0SyRqb8mYo3MEIJXB4QnVL4TOV+fD/YyGSOOJCDSo6+Lz7rEwxW3aHasOtvZnwfQiqgp3p8epbyI="
  bucket: ops-blog
  skip_cleanup: true
  detect_encoding: true
  on:
    repo: mozilla-cit/discourse-api-js
    branch: master
