language: node_js
node_js:
- '4'
sudo: false
branches:
  only:
  - master
script:
- echo "Nothing to build, no tests to run"
notifications:
  irc: irc.mozilla.org#communityops
before_deploy:
- gem install mime-types -v 2.6.2
deploy:
- provider: s3
  access_key_id: AKIAJJEWDSBN7ZUUAPFQ
  secret_access_key:
    secret: "Fq9/7KQusN/bD6Ne4nI35ZoMCRUNTZ1BO60buq8cC55hj3qAMjb4sgw8LZMhGwnRdLWRKUseG4tHk0GvqqvLsoQqxHzxg0tr9VGIfj+hx4Nb/6r2078sHbPa/ReOzF2WKi7Aw59ifJZz3w/VAzyw3B+UmUs4JLAvh8Llydr47MnDkWMdYNDzAtLU2Ip2AzCRRMml1ViYf4V3LUAe2ewZur5CdR8JLy7HlDEhwDvWfz0cf2LpCzjW4TwwWkZBGJ84/R+72Lf2AD6Sx5JQK67B0vP6hx2OhPN2L6Y1xMrT8WpkiJ3uf07vmmakgSjIfPBuJGbP3gOyL4l/MaMVxFL48uzdlYS8d9G1SLfY8MMBJKwPkXyDRb/JvvoNMAfSmWpyrWJ1uo8lHPp2n4YgLqfygZ+9bD1HQORKODeKptepvNimaWyV9KueFQwR5F8wWgEOCxDeoInX7XWHoxA75mVwdG+IatQ4xoXkqJAS1+skea+yNMFclRrBGBxyMjHeFo1Nb1x8ZZzTlTbZ4nvwQwugXj0mAwKSnh/HcxTbFXrecQ+ujNggeYHBMTSB/OkyQm996gH6Y3AYuAoSw/IIPoQy2qqZ9TBH4sOIsJqIfynqfaHxKAMuEEGmr/eXKylZWIMkDyYIeApd9coOGSX0xfZ7JCjTqM061ymGuWki0GlCHbQ="
  bucket: ops-blog
  skip_cleanup: true
  detect_encoding: true
  on:
    repo: mozilla-cit/discourse-api-js
    branch: master
